<template>
  <div>
    <v-select
      v-model="selectedCourseFilterID"
      :items="coursesFilter"
      item-text="title"
      item-value="id"
      menu-props="auto"
      label="Filter by course"
      hide-details
    ></v-select>
    <v-data-table
      :headers="headers"
      :items="filteredItem"
      sort-by="id"
      class="elevation-1"
      :loading="loading"
      loading-text="Loading... Please wait"
    >
      <template v-slot:item.fullName="{ item }">
        {{ item.firstName + " " + item.lastName }}
      </template>
      <template v-slot:item.fullAddress="{ item }">
        {{ item.address + ", " + item.postcode + ", " + item.state }}
      </template>
      <template v-slot:item.birthDate="{ item }">
        {{ getDate(item.dateOfBirth) }}
      </template>
      <template v-slot:item.course="{ item }">
        {{ getAbbreviation(item.courseId) }}
      </template>
      <template v-slot:top>
        <v-toolbar flat color="white">
          <v-toolbar-title>STUDENT LIST</v-toolbar-title>
          <v-divider class="mx-4" inset vertical></v-divider>
          <v-spacer></v-spacer>
          <v-dialog v-model="dialog" max-width="500px">
            <template v-slot:activator="{ on }">
              <v-btn color="primary" dark class="mb-2" v-on="on"
                >Add Student</v-btn
              >
            </template>
            <v-card>
              <v-card-title>
                <span class="headline">{{ formTitle }}</span>
              </v-card-title>

              <v-card-text>
                <v-container>
                  <v-row>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.id"
                        label="Student ID"
                        placeholder="Generated by System"
                        readonly
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.ic"
                        label="IC Number"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.firstName"
                        label="First Name"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.lastName"
                        label="Last Name"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.phoneNumber"
                        label="Phone Number"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.email"
                        label="Email"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="12" md="12">
                      <v-text-field
                        v-model="editedItem.address"
                        label="Address"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-text-field
                        v-model="editedItem.postcode"
                        label="Postcode"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" sm="6" md="6">
                      <v-select
                        v-model="editedItem.state"
                        :items="states"
                        menu-props="auto"
                        label="State"
                        hide-details
                      ></v-select>
                    </v-col>
                    <v-col cols="12" sm="12" md="12">
                      <v-select
                        v-model="editedItem.courseId"
                        :items="courses"
                        item-text="title"
                        item-value="id"
                        menu-props="auto"
                        label="Course"
                        hide-details
                      ></v-select>
                    </v-col>
                  </v-row>
                </v-container>
              </v-card-text>
              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="blue darken-1" text @click="close">Cancel</v-btn>
                <v-btn color="blue darken-1" text @click="save">Save</v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </v-toolbar>
      </template>
      <template v-slot:item.action="{ item }">
        <v-icon small class="mr-2" @click="editItem(item)">
          edit
        </v-icon>
        <v-icon small @click="deleteItem(item)">
          delete
        </v-icon>
      </template>
      <template v-slot:no-data>
        <v-btn color="primary" @click="initialize">Reset</v-btn>
      </template>
    </v-data-table>
  </div>
</template>

<script>
import axios from "axios";
import mykad from "mykad";
import isEmail from "validator/es/lib/isEmail";
import isNumeric from "validator/es/lib/isNumeric";
import isAlpha from "validator/es/lib/isAlpha";

const STUDENT_URL = "http://localhost:8080/api/v1/students";
const COURSE_URL = "http://localhost:8080/api/v1/courses";

export default {
  name: "StudentList",
  data: () => ({
    states: [
      "JHR",
      "KDH",
      "KTN",
      "MLK",
      "NSN",
      "PHG",
      "PNG",
      "PRK",
      "PLS",
      "SBH",
      "SWK",
      "SGR",
      "TRG",
      "KUL",
      "LBN",
      "PJY"
    ],
    dialog: false,
    headers: [
      { text: "#ID", align: "left", sortable: true, value: "id" },
      { text: "IC Number", align: "left", sortable: true, value: "ic" },
      { text: "Full Name", align: "left", sortable: true, value: "fullName" },
      { text: "Gender", align: "left", sortable: true, value: "gender" },
      {
        text: "Birth date",
        align: "left",
        sortable: true,
        value: "birthDate"
      },
      {
        text: "Phone Number",
        align: "left",
        sortable: true,
        value: "phoneNumber"
      },
      { text: "Email", align: "left", sortable: true, value: "email" },
      { text: "Address", align: "left", sortable: true, value: "fullAddress" },
      { text: "Course", align: "left", sortable: true, value: "course" },
      { text: "Actions", value: "action", sortable: false }
    ],
    items: [],
    selectedCourseFilterID: "All",
    courses: [],
    coursesFilter: [{ title: "All", abbreviation: "All" }],
    editedIndex: -1,
    editedItem: {
      ic: "",
      firstName: "",
      lastName: "",
      phoneNumber: "",
      email: "",
      postcode: "",
      address: "",
      state: "KUL",
      courseId: null
    },
    defaultItem: {
      ic: "",
      firstName: "",
      lastName: "",
      phoneNumber: "",
      email: "",
      postcode: "",
      address: "",
      state: "KUL",
      courseId: null
    },
    loading: true
  }),

  computed: {
    filteredItem: function() {
      if (this.selectedCourseFilterID == "All") {
        return this.items;
      }
      return this.items.filter(item => {
        return (
          !this.selectedCourseFilterID ||
          item.courseId === this.selectedCourseFilterID
        );
      });
    },
    formTitle: function() {
      return this.editedIndex === -1 ? "Add Student" : "Edit Student";
    }
  },

  watch: {
    dialog(val) {
      val || this.close();
    }
  },

  created() {
    this.initialize();
  },

  methods: {
    getAbbreviation: function(param) {
      let filteredCourse = this.courses.filter(course => course.id == param);
      return filteredCourse[0].abbreviation;
    },
    getDate(param) {
      let birth = new Date(param);
      return (
        birth.getDate() +
        "/" +
        (birth.getMonth() + 1) +
        "/" +
        birth.getFullYear()
      );
    },
    initialize() {
      axios
        .get(COURSE_URL)
        .then(response => {
          this.courses = response.data;
          this.coursesFilter = this.coursesFilter.concat(response.data);
        })
        .catch(error => {
          // eslint-disable-next-line no-console
          console.log(error);
        });
      axios
        .get(STUDENT_URL)
        .then(response => {
          this.items = response.data;
          this.loading = false;
        })
        .catch(error => {
          // eslint-disable-next-line no-console
          console.log(error);
        });
    },

    editItem(item) {
      this.editedIndex = this.items.indexOf(item);
      this.editedItem = Object.assign({}, item);
      this.dialog = true;
    },

    deleteItem(item) {
      const index = this.items.indexOf(item);
      confirm("Are you sure you want to delete this item?") &&
        axios
          .delete(`${STUDENT_URL}/${item.id}`)
          .then(response => {
            if (response.status == 204) {
              this.items.splice(index, 1);
            } else if (response.status == 404) {
              alert("Delete failed due to not found id.");
            } else {
              alert("Delete failed, please try again.");
            }
          })
          .catch(error => {
            // eslint-disable-next-line no-console
            console.log(error);
          });
    },

    close() {
      this.dialog = false;
      setTimeout(() => {
        this.editedItem = Object.assign({}, this.defaultItem);
        this.editedIndex = -1;
      }, 300);
    },

    save() {
      let nullCheck = param => {
        if (!param || param === null || param == "") {
          return true;
        } else {
          return false;
        }
      };

      let fieldCheck = param => {
        let flag = true;
        let msg = `Please check the following:`;

        if (nullCheck(param.ic) || !mykad.isValid(param.ic.trim())) {
          msg += `
        - IC Number`;
          flag = false;
        }
        if (
          nullCheck(param.firstName) ||
          !isAlpha(param.firstName.replace(/\s/g, ""))
        ) {
          msg += `
        - First Name`;
          flag = false;
        }
        if (
          nullCheck(param.lastName) ||
          !isAlpha(param.lastName.replace(/\s/g, ""))
        ) {
          msg += `
        - Last Name`;
          flag = false;
        }
        if (
          nullCheck(param.phoneNumber) ||
          !isNumeric(param.phoneNumber.trim())
        ) {
          msg += `
        - Phone Number`;
          flag = false;
        }
        if (nullCheck(param.email) || !isEmail(param.email.trim())) {
          msg += `
        - Email`;
          flag = false;
        }
        if (nullCheck(param.address.trim())) {
          msg += `
        - Address`;
          flag = false;
        }
        if (nullCheck(param.postcode) || !isNumeric(param.postcode.trim())) {
          msg += `
        - Postcode`;
          flag = false;
        }
        if (nullCheck(param.courseId)) {
          msg += `
        - Course`;
          flag = false;
        }
        if (!flag) {
          alert(msg);
        }
        return flag;
      };

      if (fieldCheck(this.editedItem)) {
        let mykadMetaData = mykad.parse(this.editedItem.ic, (err, data) => {
          if (err) throw err;
          return data;
        });
        this.editedItem.firstName = this.editedItem.firstName.toUpperCase();
        this.editedItem.lastName = this.editedItem.lastName.toUpperCase();
        this.editedItem.dateOfBirth = mykadMetaData.birthDate;
        this.editedItem.gender = mykadMetaData.gender[0].toUpperCase();
        for (let key in this.editedItem) {
          if (
            this.editedItem.hasOwnProperty(key) &&
            typeof this.editedItem[key] === "string"
          ) {
            this.editedItem[key] = this.editedItem[key].trim();
          }
        }

        if (this.editedIndex > -1) {
          axios
            .put(`${STUDENT_URL}/${this.editedItem.id}`, this.editedItem)
            .then(response => {
              if (response.status == 200) {
                alert("Updated successfully.");
                Object.assign(this.items[this.editedIndex], this.editedItem);
                this.close();
              } else if (response.status == 400) {
                alert("Update failed due to bad request.");
              } else if (response.status == 404) {
                alert("Update failed due to not found id.");
              } else {
                alert("Update failed, please try again.");
              }
            })
            .catch(error => {
              // eslint-disable-next-line no-console
              console.log(error);
            });
        } else {
          axios
            .post(STUDENT_URL, this.editedItem)
            .then(response => {
              if (response.status == 200) {
                alert("Added successfully.");
                this.editedItem = response.data;
                this.items.push(this.editedItem);
                this.close();
              } else if (response.status == 400) {
                alert("Add failed due to bad request(eg: duplicate).");
              } else {
                alert("Add failed, please try again.");
              }
            })
            .catch(error => {
              // eslint-disable-next-line no-console
              console.log(error);
            });
        }
      }
    }
  }
};
</script>
